version: "3.8"

services:
  wg-easy:
    image: weejewel/wg-easy:latest
    container_name: wg-easy
    environment:
      - WG_HOST=${WG_HOST}
      - WG_PORT=${WG_PORT}
      - PASSWORD_HASH=${WG_EASY_PASSWORD_HASH}
      - WG_DEVICE=${WG_DEVICE}
      - WG_ALLOWED_IPS=0.0.0.0/0,::/0
      - TZ=${TZ}
    volumes:
      - ./data/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  vpn-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: vpn-bot
    env_file:
      - .env
    environment:
      - TZ=${TZ}
    volumes:
      - ./data/bot:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - wg-easy
    restart: unless-stopped

volumes:
  # Named volumes not required; using bind mounts to keep data in repo folder
  # defined for clarity if later needed
  wg-easy-data:
  bot-data:


